name: "CI"

on:
  pull_request:
  push:

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
          extra_nix_config: |
              access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - run: nix develop --no-update-lock-file -c make
    - run: ls

    - run: gh release create $GITHUB_REF_NAME yipengsun-umd_phd_thesis.pdf
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GH_TOKEN: ${{ github.token }}
